variables:
  REGISTRY_USER: dtherhtun
  REGISTRY_PASS: i_fMsuyUzC2CZJGu-W91
  CI_REGISTRY: registry.gitlab.com
  PACKAGE_PATH: /go/src/ezy-sign
  MAJOR_TAG: registry.gitlab.com/ezysign/bastion
  ENV: CI

stages:
  - build

.anchors:
  - &inject-gopath mkdir -p ${PACKAGE_PATH}
    && ln -s ${CI_PROJECT_DIR} ${PACKAGE_PATH}
    && cd ${PACKAGE_PATH}/public

build:
  stage: build
  image: docker:latest
  services:
    - docker:19.03.5-dind
  script:
    - docker build -t $MAJOR_TAG .
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS $CI_REGISTRY
    - docker push $MAJOR_TAG
  only:
    - master

.retry:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
