apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bastion
  name: bastion
  namespace: development
spec:
  containers:
  - image: registry.gitlab.com/ezysign/bastion
    name: bastion
    ports:
    - containerPort: 22
  dnsPolicy: ClusterFirst
  restartPolicy: Always
